title : The API Report

markdown: kramdown

safe: true
lsi: false
pygments: true
auto: true

source: api-report
destination: api-report

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 10
paginate_path: "/blog/page:num"

production_url : http://api.report

BASE_PATH : http://api.report

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
